# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "RabbitKnow"
description: > # this means to ignore newlines until "email:"
    Simple thought -- Freiheit als Autonomie

email: honjunzh@gmail.com
#blog logo
logo: "/assets/images/apple-logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background-rabbit.jpg"

name: 'Zhang Hongjun'
author: 'Zhang Hongjun'
author_image: "/assets/images/apple-logo.jpg"

paginate:	5

url: "http://rabbit.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@rabbitknow'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
#social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/rabbitknow
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
